# 🚀 CONFIGURACIÓN CORRECTA PARA RENDER
# ⚠️ IMPORTANTE: Esta configuración debe coincidir exactamente con el dashboard de Render
#
# PARA APLICAR ESTOS CAMBIOS:
# 1. Ve al dashboard de Render → Settings
# 2. Copia exactamente esta configuración
# 3. Configura las Secret Files mencionadas abajo
# 4. Redeploy manualmente

services:
  - type: web
    name: bruceapp-frontend
    env: node
    # ✅ CORRECCIÓN 1: Build command simplificado (sin npm ci)
    buildCommand: npm run build
    startCommand: npm run start
    # ✅ CORRECCIÓN 2: Puerto dinámico para compatibilidad con Render
    # Render asigna PORT automáticamente (10000 o similar)
    envVars:
      - key: NODE_ENV
        value: production
      # ✅ CORRECCIÓN 3: Node.js version específica
      - key: NODE_VERSION
        value: 18.20.4
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      # ✅ CORRECCIÓN 4: URL pública correcta
      - key: NEXT_PUBLIC_API_URL
        value: https://bruceapponrender.com
    
    # 🔒 SECRET FILES REQUERIDOS (configurar en dashboard):
    # 1. JWT_SECRET: Generar con: openssl rand -base64 32
    # 2. MONGODB_URI: Connection string de MongoDB Atlas
    # 3. OPENAI_API_KEY: API key de OpenAI (sk-...)
    
    autoDeploy: true
    healthCheckPath: /
    plan: free
