# Configuración de referencia para Render Web Services
# ⚠️  NO se usa automáticamente - configura manualmente en el dashboard de Render
#
# Frontend Service Configuration:
# - Build Command: npm run build
# - Start Command: npm run start
# - Environment Variables: NODE_ENV=production, OPENAI_API_KEY, JWT_SECRET, NEXT_PUBLIC_API_URL

services:
  - type: web
    name: bruceapp-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    port: 3000
    autoDeploy: false
    healthCheckPath: /
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Configure these secrets in Render dashboard:
      - key: OPENAI_API_KEY
        fromSecret: openai-api-key
      - key: JWT_SECRET
        fromSecret: jwt-secret
      # Update this with your actual API service URL after deployment
      - key: NEXT_PUBLIC_API_URL
        value: https://your-api-service-name.onrender.com
